// source: customer_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var customer_pb = require('./customer_pb.js');
goog.object.extend(proto, customer_pb);
goog.exportSymbol('proto.dev.mgray.server.service.customer.AddCustomerRequest', null, global);
goog.exportSymbol('proto.dev.mgray.server.service.customer.LoginErrorCode', null, global);
goog.exportSymbol('proto.dev.mgray.server.service.customer.LoginRequest', null, global);
goog.exportSymbol('proto.dev.mgray.server.service.customer.LoginRequest.MethodCase', null, global);
goog.exportSymbol('proto.dev.mgray.server.service.customer.LoginResponse', null, global);
goog.exportSymbol('proto.dev.mgray.server.service.customer.UserNamePasswordBundle', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dev.mgray.server.service.customer.AddCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dev.mgray.server.service.customer.AddCustomerRequest.displayName = 'proto.dev.mgray.server.service.customer.AddCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dev.mgray.server.service.customer.LoginRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.dev.mgray.server.service.customer.LoginRequest.oneofGroups_);
};
goog.inherits(proto.dev.mgray.server.service.customer.LoginRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dev.mgray.server.service.customer.LoginRequest.displayName = 'proto.dev.mgray.server.service.customer.LoginRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dev.mgray.server.service.customer.UserNamePasswordBundle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dev.mgray.server.service.customer.UserNamePasswordBundle.displayName = 'proto.dev.mgray.server.service.customer.UserNamePasswordBundle';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dev.mgray.server.service.customer.LoginResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dev.mgray.server.service.customer.LoginResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dev.mgray.server.service.customer.LoginResponse.displayName = 'proto.dev.mgray.server.service.customer.LoginResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dev.mgray.server.service.customer.AddCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dev.mgray.server.service.customer.AddCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerInfo: (f = msg.getCustomerInfo()) && customer_pb.CustomerInfo.toObject(includeInstance, f),
    password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dev.mgray.server.service.customer.AddCustomerRequest}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dev.mgray.server.service.customer.AddCustomerRequest;
  return proto.dev.mgray.server.service.customer.AddCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dev.mgray.server.service.customer.AddCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dev.mgray.server.service.customer.AddCustomerRequest}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new customer_pb.CustomerInfo;
      reader.readMessage(value,customer_pb.CustomerInfo.deserializeBinaryFromReader);
      msg.setCustomerInfo(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dev.mgray.server.service.customer.AddCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dev.mgray.server.service.customer.AddCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      customer_pb.CustomerInfo.serializeBinaryToWriter
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional dev.mgray.db.schema.customer.CustomerInfo customer_info = 1;
 * @return {?proto.dev.mgray.db.schema.customer.CustomerInfo}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.getCustomerInfo = function() {
  return /** @type{?proto.dev.mgray.db.schema.customer.CustomerInfo} */ (
    jspb.Message.getWrapperField(this, customer_pb.CustomerInfo, 1));
};


/**
 * @param {?proto.dev.mgray.db.schema.customer.CustomerInfo|undefined} value
 * @return {!proto.dev.mgray.server.service.customer.AddCustomerRequest} returns this
*/
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.setCustomerInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dev.mgray.server.service.customer.AddCustomerRequest} returns this
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.clearCustomerInfo = function() {
  return this.setCustomerInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.hasCustomerInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dev.mgray.server.service.customer.AddCustomerRequest} returns this
 */
proto.dev.mgray.server.service.customer.AddCustomerRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.dev.mgray.server.service.customer.LoginRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.dev.mgray.server.service.customer.LoginRequest.MethodCase = {
  METHOD_NOT_SET: 0,
  USERNAME_PASSWORD: 1,
  SESSION: 2
};

/**
 * @return {proto.dev.mgray.server.service.customer.LoginRequest.MethodCase}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.getMethodCase = function() {
  return /** @type {proto.dev.mgray.server.service.customer.LoginRequest.MethodCase} */(jspb.Message.computeOneofCase(this, proto.dev.mgray.server.service.customer.LoginRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dev.mgray.server.service.customer.LoginRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dev.mgray.server.service.customer.LoginRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.LoginRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    usernamePassword: (f = msg.getUsernamePassword()) && proto.dev.mgray.server.service.customer.UserNamePasswordBundle.toObject(includeInstance, f),
    session: (f = msg.getSession()) && customer_pb.Session.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest}
 */
proto.dev.mgray.server.service.customer.LoginRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dev.mgray.server.service.customer.LoginRequest;
  return proto.dev.mgray.server.service.customer.LoginRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dev.mgray.server.service.customer.LoginRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest}
 */
proto.dev.mgray.server.service.customer.LoginRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dev.mgray.server.service.customer.UserNamePasswordBundle;
      reader.readMessage(value,proto.dev.mgray.server.service.customer.UserNamePasswordBundle.deserializeBinaryFromReader);
      msg.setUsernamePassword(value);
      break;
    case 2:
      var value = new customer_pb.Session;
      reader.readMessage(value,customer_pb.Session.deserializeBinaryFromReader);
      msg.setSession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dev.mgray.server.service.customer.LoginRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dev.mgray.server.service.customer.LoginRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.LoginRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsernamePassword();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.dev.mgray.server.service.customer.UserNamePasswordBundle.serializeBinaryToWriter
    );
  }
  f = message.getSession();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      customer_pb.Session.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserNamePasswordBundle username_password = 1;
 * @return {?proto.dev.mgray.server.service.customer.UserNamePasswordBundle}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.getUsernamePassword = function() {
  return /** @type{?proto.dev.mgray.server.service.customer.UserNamePasswordBundle} */ (
    jspb.Message.getWrapperField(this, proto.dev.mgray.server.service.customer.UserNamePasswordBundle, 1));
};


/**
 * @param {?proto.dev.mgray.server.service.customer.UserNamePasswordBundle|undefined} value
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest} returns this
*/
proto.dev.mgray.server.service.customer.LoginRequest.prototype.setUsernamePassword = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.dev.mgray.server.service.customer.LoginRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest} returns this
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.clearUsernamePassword = function() {
  return this.setUsernamePassword(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.hasUsernamePassword = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional dev.mgray.db.schema.customer.Session session = 2;
 * @return {?proto.dev.mgray.db.schema.customer.Session}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.getSession = function() {
  return /** @type{?proto.dev.mgray.db.schema.customer.Session} */ (
    jspb.Message.getWrapperField(this, customer_pb.Session, 2));
};


/**
 * @param {?proto.dev.mgray.db.schema.customer.Session|undefined} value
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest} returns this
*/
proto.dev.mgray.server.service.customer.LoginRequest.prototype.setSession = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.dev.mgray.server.service.customer.LoginRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dev.mgray.server.service.customer.LoginRequest} returns this
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.clearSession = function() {
  return this.setSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dev.mgray.server.service.customer.LoginRequest.prototype.hasSession = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.toObject = function(opt_includeInstance) {
  return proto.dev.mgray.server.service.customer.UserNamePasswordBundle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.toObject = function(includeInstance, msg) {
  var f, obj = {
    userName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dev.mgray.server.service.customer.UserNamePasswordBundle;
  return proto.dev.mgray.server.service.customer.UserNamePasswordBundle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dev.mgray.server.service.customer.UserNamePasswordBundle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string user_name = 1;
 * @return {string}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.getUserName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle} returns this
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.setUserName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dev.mgray.server.service.customer.UserNamePasswordBundle} returns this
 */
proto.dev.mgray.server.service.customer.UserNamePasswordBundle.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dev.mgray.server.service.customer.LoginResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dev.mgray.server.service.customer.LoginResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.LoginResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    customerId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    session: (f = msg.getSession()) && customer_pb.Session.toObject(includeInstance, f),
    errorCode: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse}
 */
proto.dev.mgray.server.service.customer.LoginResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dev.mgray.server.service.customer.LoginResponse;
  return proto.dev.mgray.server.service.customer.LoginResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dev.mgray.server.service.customer.LoginResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse}
 */
proto.dev.mgray.server.service.customer.LoginResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCustomerId(value);
      break;
    case 2:
      var value = new customer_pb.Session;
      reader.readMessage(value,customer_pb.Session.deserializeBinaryFromReader);
      msg.setSession(value);
      break;
    case 3:
      var value = /** @type {!proto.dev.mgray.server.service.customer.LoginErrorCode} */ (reader.readEnum());
      msg.setErrorCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dev.mgray.server.service.customer.LoginResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dev.mgray.server.service.customer.LoginResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dev.mgray.server.service.customer.LoginResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomerId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getSession();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      customer_pb.Session.serializeBinaryToWriter
    );
  }
  f = message.getErrorCode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional int64 customer_id = 1;
 * @return {number}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.getCustomerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse} returns this
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.setCustomerId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional dev.mgray.db.schema.customer.Session session = 2;
 * @return {?proto.dev.mgray.db.schema.customer.Session}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.getSession = function() {
  return /** @type{?proto.dev.mgray.db.schema.customer.Session} */ (
    jspb.Message.getWrapperField(this, customer_pb.Session, 2));
};


/**
 * @param {?proto.dev.mgray.db.schema.customer.Session|undefined} value
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse} returns this
*/
proto.dev.mgray.server.service.customer.LoginResponse.prototype.setSession = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse} returns this
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.clearSession = function() {
  return this.setSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.hasSession = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LoginErrorCode error_code = 3;
 * @return {!proto.dev.mgray.server.service.customer.LoginErrorCode}
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.getErrorCode = function() {
  return /** @type {!proto.dev.mgray.server.service.customer.LoginErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.dev.mgray.server.service.customer.LoginErrorCode} value
 * @return {!proto.dev.mgray.server.service.customer.LoginResponse} returns this
 */
proto.dev.mgray.server.service.customer.LoginResponse.prototype.setErrorCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.dev.mgray.server.service.customer.LoginErrorCode = {
  UNKNOWN: 0,
  USER_NAME_ALREADY_IN_USE: 1,
  INVALID_CREDENTIALS: 2
};

goog.object.extend(exports, proto.dev.mgray.server.service.customer);
